### PR TITLE
Fix Box Model Math link

### PR DESCRIPTION
**Pull request by chigley**

### CODE REVIEW

**Comment by aguynamedloren** [comment]
Heh, beat me to it.  :+1: 

Highly unlikely that it matters in this particular case, but it's probably best to change the link instead of the the anchor, in the off chance that somebody has linked to the anchor from elsewhere.

**Comment by chigley** [comment]
Thanks for the tip!

I must admit my decision was fairly arbitrary - I had a mini internal battle with myself over which alternative was best, but couldn't think of any reason to choose one over the other. You raise a good point though, thanks :+1:

**Comment by xixixao** [comment]
:+1:

**Comment by mdo** [comment]
Thanks!

**Pull request merged**
